Repository HansGabriel/TestTrek, pull requests merged in 2023-10, with the labels that each got.

#112 Jetdieron01/tes 134
  apps/expo/src/forms/CreateTestForm.tsx
  apps/expo/src/icons/playtest/PlayTestBackground.tsx
  apps/expo/src/screens/profile.tsx
  apps/expo/src/screens/settings/index.tsx
Labels: enhancement

#116 jetdieron01/tes 118
  apps/expo/src/components/modals/OptionModal.tsx
  apps/expo/src/icons/WatchTimerIcon.tsx
  apps/expo/src/screens/play-test/CountdownTimer.tsx
  apps/expo/src/screens/play-test/index.tsx
Labels: enhancement

#120 jetdieron01/tes 145
  apps/expo/src/screens/create-question/index.tsx
  packages/api/src/functions/gptHandlers.ts
Labels: enhancement

#124 refactor: keyword now resets on save test
  apps/expo/src/components/inputs/MultipleTextInput.tsx
  apps/expo/src/forms/CreateTestForm.tsx
  apps/expo/src/screens/create-question/index.tsx
Labels: bug

#127 refactor: view all now shows all items instead of 5
  apps/expo/src/components/Discover/DiscoverHomeSection.tsx
  apps/expo/src/components/HomeTestDisplayCard.tsx
  apps/expo/src/components/top-collections/TopCollectionsHomeSection.tsx
  apps/expo/src/components/top-picks-tests/TopPicksHomeSection.tsx
  apps/expo/src/components/top-trekers/TopTrekersHomeSection.tsx
  apps/expo/src/components/trending-tests/TrendingTestsHomeSection.tsx
  apps/expo/src/components/view-all-display/tests/ViewAllTestDisplay.tsx
  packages/api/src/router/collection.ts
  packages/api/src/router/test.ts
  packages/api/src/router/user.ts
  packages/schema/src/collection.ts
  packages/schema/src/test.ts
  packages/schema/src/user.ts
Labels: enhancement

#129 jetdieron01/tes 142
  apps/expo/src/components/bottom-sheet/ChoiceBottomSheet.tsx
  apps/expo/src/forms/CreateTestForm.tsx
  apps/expo/src/screens/settings/index.tsx
Labels: bug, enhancement

#130 jetdieron01/tes 149
  apps/expo/src/forms/CreateTestForm.tsx
  apps/expo/src/screens/create-question/index.tsx
  apps/expo/src/screens/play-test/index.tsx
  apps/expo/src/screens/settings/index.tsx
Labels: enhancement

#133 refactor: handled long texts; changed long texts logic
  apps/expo/src/components/my-collections/Collections.tsx
  apps/expo/src/components/my-library/LibraryTabs.tsx
  apps/expo/src/components/my-reviewer/ReviewerTab.tsx
  apps/expo/src/components/profile-details/details-section/OthersProfileDetailsSection.tsx
  apps/expo/src/components/profile-details/details-section/ProfileDetailsSection.tsx
  apps/expo/src/components/profile-details/profile-buttons/ViewStatisticsButton.tsx
  apps/expo/src/components/test-details/TestDetailsContent.tsx
  apps/expo/src/components/view-all-display/collections/CollectionsCard.tsx
  apps/expo/src/navigation/index.tsx
  packages/api/src/router/collection.ts
  packages/schema/src/collection.ts
Labels: bug, enhancement

#136 added: unit tests for gptHandler functions
  packages/api/src/functions/generatePromptForType.test.ts
  packages/api/src/functions/parseQuestionTypeResponse.test.ts
Labels: enhancement

#150 jetdieron01/tes 154
  packages/api/src/functions/constants.ts
  packages/api/src/functions/generatePromptForType.test.ts
  packages/api/src/functions/gptHandlers.ts
  packages/api/src/functions/parseQuestionTypeResponse.test.ts
Labels: enhancement

#151 Jetdieron01/tes 166
  packages/api/src/functions/gptHandlers.ts
  packages/api/src/functions/testCreationHandlers.ts
  packages/api/src/router/gptApi.ts
  packages/schema/src/gpt.ts
Labels: enhancement

#154 gptHandlers refactoring
  packages/api/src/functions/generatePromptForType.test.ts
  packages/api/src/functions/gptHandlers.ts
  packages/api/src/functions/testCreationHandlers.test.ts
  packages/api/src/functions/testCreationHandlers.ts
  packages/schema/src/gpt.ts
Labels: enhancement

#156 refactor: removed redundant logic
  packages/api/src/functions/testCreationHandlers.test.ts
  packages/api/src/functions/testCreationHandlers.ts
Labels: enhancement

#160 added: initial tests for playTest router; refactor: test files locations
  apps/expo/src/functions/tests/timeAgo.test.ts
  apps/expo/unit-tests/index.test.ts
  packages/api/src/functions/gptApiHandlers.ts
  packages/api/src/functions/tests/generatePromptForType.test.ts
  packages/api/src/functions/tests/parseQuestionTypeResponse.test.ts
  packages/api/src/functions/tests/testCreationHandlers.test.ts
  packages/api/src/router-tests/sample.test.ts
  packages/api/src/router/gptApi.ts
  packages/api/src/router/tests/mockCtx.ts
  packages/api/src/router/tests/play.test.ts
Labels: question

#165 TES-189: Functionality to add tests to collections
  apps/expo/src/components/buttons/AppButton.tsx
  apps/expo/src/components/headers/ReusableHeader.tsx
  apps/expo/src/forms/CreateTestForm/index.tsx
  apps/expo/src/screens/edit-collection/RightSidebar.tsx
  apps/expo/src/screens/edit-collection/index.tsx
  apps/expo/src/screens/edit-test.tsx
  packages/api/src/router/collection.ts
  packages/api/src/router/test.ts
  packages/db/prisma/schema.prisma
  packages/schema/src/test.ts
Labels: enhancement

#170 added: logic for trending and top picks test
  packages/api/src/router/test.ts
  packages/api/src/router/tests/testQueries.test.ts
Labels: enhancement
